trigger:
  - main

pr:
  - main

parameters:
  - name: platforms
    type: object
    default:
      - name: Linux
        image: ubuntu-latest
      - name: macOS
        image: macOS-15
      - name: Windows
        image: windows-latest

variables:
  buildConfiguration: 'Debug'
  dotnetVersion: '9.0.x'

stages:
  - ${{ each platform in parameters.platforms }}:
    - stage: BuildAndTest_${{ platform.name }}
      displayName: '${{ platform.name }}'
      #dependsOn: []
      jobs:
        - job: Build_${{ platform.name }}
          displayName: 'Build on ${{ platform.name }}'
          pool:
            vmImage: ${{ platform.image }}
          steps:
            - template: azure-template-setup.yml
            - task: DotNetCoreCLI@2
              displayName: 'Build solution'
              inputs:
                command: 'build'
                projects: '**/*.sln'
                arguments: '--configuration $(buildConfiguration)'

        - job: Test_${{ platform.name }}
          displayName: 'Tests on ${{ platform.name }}'
          #dependsOn: Build_${{ platform.name }}
          pool:
            vmImage: ${{ platform.image }}
          steps:
            - template: azure-template-setup.yml
            - task: DotNetCoreCLI@2
              displayName: 'Run tests'
              inputs:
                command: 'test'
                projects: '**/tests/**/*.csproj'
                arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage"'
                publishTestResults: true
            - task: PublishCodeCoverageResults@2
              displayName: 'Publish code coverage'
              condition: succeededOrFailed()
              inputs:
                codeCoverageTool: 'Cobertura'
                summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
                reportDirectory: '$(Agent.TempDirectory)/**/coverage'

  - stage: PostSummaryComment
    displayName: 'Post Summary Comment'
    dependsOn: 
      - BuildAndTest_Linux
      - BuildAndTest_macOS
      - BuildAndTest_Windows
    jobs:
      - job: PostComment
        displayName: 'Post GitHub Summary Comment'
        pool:
          vmImage: ubuntu-latest
        steps:
          - pwsh: ./scripts/post-build-summary.ps1
            displayName: 'Generate and Post Build Summary Comment'
