name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    env:
      COPILOT_BUILD_RUN: true
    
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install the .NET MAUI workload
        run: dotnet workload install maui-android

      - name: Validate environment variables
        run: pwsh ./scripts/validate-env-vars.ps1

      - name: Run a pre-work build
        continue-on-error: true
        run: dotnet build
