name: "Copilot Approve Post PR Failure Comments Workflows"

on:
  workflow_dispatch:       # Allows manual triggering
  schedule:
    - cron: "*/30 * * * *" # Every 30 minutes

jobs:
  approve-pending-workflows:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Approve pending comment workflows
        uses: ./.github/actions/copilot-approve-pending-workflows
        with:
          workflow: "Copilot Post PR Failure Comments"
