name: "Copilot Approve Post PR Failure Comments Workflows"

on:
  workflow_dispatch:       # Allows manual triggering
  schedule:
    - cron: "*/30 * * * *" # Every 30 minutes

jobs:
  approve-pending-workflows:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Approve pending comment workflows
      shell: pwsh
      env:
        GH_TOKEN: ${{ secrets.BUILD_STATUS_COMMENT || secrets.GITHUB_TOKEN }}
      run: |
        ./.github/scripts/copilot-approve-pending-workflows.ps1 `
          -Repository "${{ github.repository }}" `
          -WorkflowName "Copilot Post PR Failure Comments"
