name: "Copilot Post PR Failure Comments"

on:
  check_suite:
    types: [completed]

jobs:
  post-failure-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Print all
        shell: pwsh
        run: echo "${{ toJSON(github) }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Post any failure comments
        uses: ./.github/actions/copilot-post-failure-comment
        with:
          token: ${{ secrets.BUILD_STATUS_COMMENT }}
          max-comments: 5
