name: "List Pending Approvals"

on:
  workflow_dispatch:
  schedule:
    # Run daily at 9 AM UTC
    - cron: '0 9 * * *'

jobs:
  list-pending-approvals:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      pull-requests: read
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: List PRs with pending workflow approvals
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./.github/scripts/list-pending-approvals.ps1 -OutputFormat "detailed"